### ISSUE TITLE
"TypeError: <lambda>() takes no arguments (1 given)" on ./bin/instance start

### ISSUE THREAD

**Issue by agitator** [plone/plone.recipe.zope2instance#23]
```
hope:project peter$ ./bin/instance start
Traceback (most recent call last):
  File "./bin/instance", line 265, in <module>
    + sys.argv[1:]))
  File "/Users/peter/workspace/project/eggs/plone.recipe.zope2instance-4.2.20-py2.7.egg/plone/recipe/zope2instance/ctl.py", line 612, in main
    c.onecmd(' '.join(options.args))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/Users/peter/workspace/project/eggs/plone.recipe.zope2instance-4.2.20-py2.7.egg/plone/recipe/zope2instance/ctl.py", line 374, in do_start
    "daemon process started, pid=%(zd_pid)d")
  File "/Users/peter/workspace/project/eggs/zdaemon-4.1.0-py2.7.egg/zdaemon/zdctl.py", line 271, in awhile
    while not cond(n):
TypeError: <lambda>() takes no arguments (1 given)
hope:project peter$ 
 
```

**Comment by jensens** [comment]
same here
