### ISSUE TITLE
Builds are failing on TravisCI

### ISSUE THREAD

**Issue by icemac** [plone/plone.recipe.zope2instance#98]
See https://travis-ci.org/plone/plone.recipe.zope2instance

The reason seems to be the `pyproject.toml` file which makes `pip` think it should use instead of `setup.py`.

**Comment by icemac** [comment]
This issue breaks #99 and possible subsequent PR.

**Comment by dataflake** [comment]
It breaks local testing with `tox` as well. I could only get it to run by moving `pyproject.toml` to the side.

The tests run under Python 2, but under all versions of Python 3 I get a very strange error:

```
----------------------------------------------------------------------
File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/src/plone/recipe/zope2instance/tests/zope2instance.txt", line 33, in zope2instance.txt
Failed example:
    print(system(join('bin', 'buildout'))),
Differences (ndiff with -expected +actual):
    - Installing instance.
    - Generated script '...instance'.
    - Generated interpreter '.../parts/instance/bin/interpreter'...
    + Traceback (most recent call last):
    +   File "bin/buildout", line 8, in <module>
    +     import zc.buildout.buildout
    +   File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/.tox/py37/lib/python3.7/site-packages/zc/buildout/buildout.py", line 18, in <module>
    +     import zc.buildout.easy_install
    +   File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/.tox/py37/lib/python3.7/site-packages/zc/buildout/easy_install.py", line 29, in <module>
    +     import setuptools.archive_util
    +   File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/.tox/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 20, in <module>
    +     from setuptools.dist import Distribution, Feature
    +   File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/.tox/py37/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
    +     from setuptools.depends import Require
    +   File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/.tox/py37/lib/python3.7/site-packages/setuptools/depends.py", line 7, in <module>
    +     from .py33compat import Bytecode
    +   File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/.tox/py37/lib/python3.7/site-packages/setuptools/py33compat.py", line 11, in <module>
    +     from setuptools.extern.six.moves import html_parser
    +   File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/.tox/py37/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 92, in __get__
    +     result = self._resolve()
    +   File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/.tox/py37/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 115, in _resolve
    +     return _import_module(self.mod)
    +   File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/.tox/py37/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 82, in _import_module
    +     __import__(name)
    +   File "/opt/dev/5Ms_buildout/src/plone.recipe.zope2instance/.tox/py37/lib/python3.7/site-packages/html/__init__.py", line 7, in <module>
    +     raise ImportError('This package should not be accessible on Python 3. '
    + ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
    + <BLANKLINE>
    + (None,)
```
